/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2019-12-18 00:34:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>인테리어소품 코제트</title>\r\n");
      out.write("<link href=\"../../css/join.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function check(){\r\n");
      out.write("\tvar form = document.form1;\r\n");
      out.write("\tvar userId = document.getElementById('userId').value.trim();\r\n");
      out.write("\tif(userId.length ==0){\r\n");
      out.write("\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    function sample6_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var fullAddr = ''; // 최종 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    fullAddr = data.roadAddress;\r\n");
      out.write("\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    fullAddr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    //법정동명이 있을 경우 추가한다.\r\n");
      out.write("                    if(data.bname !== ''){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있을 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== ''){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.\r\n");
      out.write("                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample6_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                document.getElementById('sample6_address').value = fullAddr;\r\n");
      out.write("\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById('daddress').focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("function validatePhoneNum2() {\r\n");
      out.write("\tvar phoneNum2 = document.getElementById('phoneNum2').value.trim();\r\n");
      out.write("\tvar alertEl = document.getElementById('phoneNum2_alert');\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 입력 여부 검증\r\n");
      out.write("\tif (phoneNum2.length == 0) {\r\n");
      out.write("\t\talertEl.innerHTML = '필수 정보입니다.';\r\n");
      out.write("\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t//  숫자 입력 검증\r\n");
      out.write("\tif (!/^[A-Za-z!?#$%]*$/.test(phoneNum2)) {\r\n");
      out.write("\t\talertEl.innerHTML = '';\r\n");
      out.write("\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\talertEl.style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validatePhoneNum3() {\r\n");
      out.write("\tvar phoneNum3 = document.getElementById('phoneNum3').value.trim();\r\n");
      out.write("\tvar alertEl = document.getElementById('phoneNum3_alert');\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 입력 여부 검증\r\n");
      out.write("\tif (phoneNum3.length == 0) {\r\n");
      out.write("\t\talertEl.innerHTML = '';\r\n");
      out.write("\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t//  숫자 입력 검증\r\n");
      out.write("\tif (!/^[A-Za-z!?#$%]*$/.test(phoneNum3)) {\r\n");
      out.write("\t\talertEl.innerHTML = '';\r\n");
      out.write("\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\talertEl.style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateUserId() {\r\n");
      out.write("\t\tvar userId = document.getElementById('userId').value.trim();\r\n");
      out.write("\t\tvar alertEl = document.getElementById('userId_alert');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 입력 여부 검증\r\n");
      out.write("\t\tif (userId.length == 0) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '필수 정보입니다.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 길이 검증\r\n");
      out.write("\t\tif (userId.length < 5) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '아이디는 4글자 이상 입력해주세요.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\talertEl.style.color =\"red\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 대소문자, 숫자 입력 검증\r\n");
      out.write("\t\tif (!/^[A-Za-z0-9]*$/.test(userId)) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '아이디는 영문 대문자,소문자, 숫자만 입력 가능합니다.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\talertEl.style.color =\"red\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talertEl.style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validatePassword() {\r\n");
      out.write("\t\tvar password = document.getElementById('password').value.trim();\r\n");
      out.write("\t\tvar alertEl = document.getElementById('password_alert');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호 입력 여부 검증\r\n");
      out.write("\t\tif (password.length == 0) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '필수 정보입니다.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호 길이 검증\r\n");
      out.write("\t\tif (password.length < 5) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '비밀번호는 5글자 이상 입력해주세요.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\talertEl.style.color =\"red\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 비밀번호 대소문자, 숫자 입력 검증\r\n");
      out.write("\t\tif (!/^[A-Za-z0-9!?#$%]*$/.test(password)) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '비밀번호는 영문 대문자,소문자, 숫자만 입력 가능합니다.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\talertEl.style.color =\"red\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\talertEl.style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("function validatePassword2() \r\n");
      out.write("{\r\n");
      out.write("\tvar password = document.getElementById('password').value.trim();\r\n");
      out.write("\tvar password2 = document.getElementById('password2').value.trim();\r\n");
      out.write("\tvar alertEl = document.getElementById('password2_alert');\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 비밀번호 길이 검증\r\n");
      out.write("\tif (password2.length < 5) {\r\n");
      out.write("\t\talertEl.innerHTML = '비밀번호는 5글자 이상 입력해주세요.';\r\n");
      out.write("\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\talertEl.style.color =\"red\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 비밀번호 대소문자, 숫자 입력 검증\r\n");
      out.write("\tif (!/^[A-Za-z0-9!?#$%]*$/.test(password2)) {\r\n");
      out.write("\t\talertEl.innerHTML = '비밀번호는 영문 대문자,소문자, 숫자만 입력 가능합니다.';\r\n");
      out.write("\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\talertEl.style.color =\"red\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 비밀번호, 비밀번호 확인 검증\r\n");
      out.write("\tif (password != password2) {\r\n");
      out.write("\t\talertEl.innerHTML = '비밀번호가 일치하지 않습니다.';\r\n");
      out.write("\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\talertEl.style.color =\"red\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\talertEl.style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateUserName() {\r\n");
      out.write("\t\tvar userName = document.getElementById('userName').value.trim();\r\n");
      out.write("\t\tvar alertEl = document.getElementById('userName_alert');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 입력 여부 검증\r\n");
      out.write("\t\tif (userName.length == 0) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '필수 정보입니다.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talertEl.style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateEmail1() {\r\n");
      out.write("\t\tvar email1 = document.getElementById('email1').value.trim();\r\n");
      out.write("\t\tvar alertEl = document.getElementById('email1_alert');\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 입력 여부 검증\r\n");
      out.write("\t\tif (email1.length == 0) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '필수정보 입니다.';\r\n");
      out.write("\t\t\talertEl.style.display = 'inline';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction validateEmail2() {\r\n");
      out.write("\t\t\tvar email2 = document.getElementById('email2').value.trim();\r\n");
      out.write("\t\t\tvar alertEl = document.getElementById('email2_alert');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 입력 여부 검증\r\n");
      out.write("\t\t\tif (email2.length == 0) {\r\n");
      out.write("\t\t\t\talertEl.innerHTML = ' ';\r\n");
      out.write("\t\t\t\talertEl.style.display = 'inline';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateBirth() {\r\n");
      out.write("\t\tvar birthYear = document.getElementById('birth_year').value.trim();\r\n");
      out.write("\t\tvar birthDay = document.getElementById('birth_day').value.trim();\r\n");
      out.write("\t\tvar alertEl = document.getElementById('birth_alert');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (birthYear.length == 0) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '태어난 년도 4자리를 입력해주세요.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (birthDay.length == 0) {\r\n");
      out.write("\t\t\talertEl.innerHTML = '태어난 일자를 입력해주세요.';\r\n");
      out.write("\t\t\talertEl.style.display = 'block';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!/^[0-9]*$/.test(birthYear)) {\r\n");
      out.write("\t\t\tbirth_alert.innerHTML = '태어난 년도는 숫자만 입력 가능합니다.';\r\n");
      out.write("\t\t\tbirth_alert.style.display = 'block';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (!/^[0-9]*$/.test(birthDay)) {\r\n");
      out.write("\t\t\tbirth_alert.innerHTML = '태어난 일자는 숫자만 입력 가능합니다.';\r\n");
      out.write("\t\t\tbirth_alert.style.display = 'block';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talertEl.style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction hotinsert( param )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar input = document.getElementById('email2')\r\n");
      out.write("\t\tinput.value=param\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=wrap>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../form/header.jsp", out, true);
      out.write("\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("\t<div class=table_area>\r\n");
      out.write("\t<form action=\"joinFinish.jsp\" method=\"post\" name=\"form1\">\r\n");
      out.write("\t\t<table class=\"type03\" border=\"1\" cellpadding=\"3\" cellspacing=\"0\">\r\n");
      out.write("\t\t \r\n");
      out.write("        <tr>\r\n");
      out.write("        <th bgcolor=\"#eeeeee\" scope=\"row\">아이디<span class=\"list\"> *</span></th>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"userId\" name=\"userId\" class=\"input-text\" placeholder=\"아이디\" maxlength=\"20\" onfocusout=\"validateUserId()\"/>\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"중복확인\"/>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"userId_alert\" class=\"alert\">공백없이 4~16자의 영문/숫자를 조합하여 입력해주세요.</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("          <th bgcolor=\"#eeeeee\" scope=\"row\">비밀번호 <span class=\"list\">*</span></th>\r\n");
      out.write("          <td>\r\n");
      out.write("          <span>\r\n");
      out.write("               <input type=\"password\" name=\"password\" id=\"password\" class=\"input-text\" placeholder=\"비밀번호\" maxlength=\"20\" onfocusout=\"validatePassword()\"/>\r\n");
      out.write("    \t  </span>      \r\n");
      out.write("    \t  <div id=\"password_alert\" class=\"alert\"> 공백없이 8~15자의 영문/숫자를 조합하여 입력해주세요.</div>\r\n");
      out.write("         </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th bgcolor=\"#eeeeee\" scope=\"row\">비밀번호 확인 <span class=\"list\">*</span></th>\r\n");
      out.write("          <td>\r\n");
      out.write("            <span>\r\n");
      out.write("            <input type=\"password\" name=\"password2\" id=\"password2\" class=\"input-text\" placeholder=\"비밀번호\" maxlength=\"20\" onfocusout=\"validatePassword2()\" />\r\n");
      out.write("            </span>      \r\n");
      out.write("              <div id=\"password2_alert\" class=\"alert\"> 비밀번호 확인을 위해 다시 한 번 입력해주세요.</div>\r\n");
      out.write("         \r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("          <th bgcolor=\"#eeeeee\" scope=\"row\">이름 <span class=\"list\">*</span></th>\r\n");
      out.write("          <td>\r\n");
      out.write("          \t<span>\r\n");
      out.write("            \t<input type=\"text\" name=\"userName\" id=\"userName\" class=\"input-text\" placeholder=\"이름\" maxlength=\"20\" onfocusout=\"validateUserName()\"/>\r\n");
      out.write("           \t</span>\r\n");
      out.write("          <div id=\"userName_alert\" class=\"alert\"></div>\r\n");
      out.write("        </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("          <th width=\"122\" height=\"46\" bgcolor=\"#eeeeee\" scope=\"row\">휴대폰 번호 <span class=\"list\">*</span></th>\r\n");
      out.write("          <td width=\"560\">\r\n");
      out.write("            <select name=\"phoneNum1\" id=\"phoneNum1\" style=\"width: 200px; height: 30px;\">\r\n");
      out.write("              <option value=\"010\">010</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            -\r\n");
      out.write("            \r\n");
      out.write("            <span>\r\n");
      out.write("            <input type=\"number\" name=\"phoneNum2\" id=\"phoneNum2\" class=\"input-text\" placeholder=\"휴대폰번호\" maxlength=\"20\" onfocusout=\"validatePhoneNum2()\" />\r\n");
      out.write("            </span>\r\n");
      out.write("            \r\n");
      out.write("            -\r\n");
      out.write("\t\t\t <span>\r\n");
      out.write("            <input type=\"number\" name=\"phoneNum3\" id=\"phoneNum3\" class=\"input-text\" placeholder=\"휴대폰번호\" maxlength=\"20\" onfocusout=\"validatePhoneNum3()\" />\t\t\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"phoneNum2_alert\" class=\"alert\"></div>\r\n");
      out.write("\t\t\t<div id=\"phoneNum3_alert\" class=\"alert\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("          <th bgcolor=\"#eeeeee\" scope=\"row\">이메일 <span class=\"list\">*</span></th>\r\n");
      out.write("          <td>\r\n");
      out.write("           <div>\r\n");
      out.write("            <input type=\"text\" name=\"email1\" id=\"email1\" class=\"input-text\" placeholder=\"이메일\" maxlength=\"20\" onfocusout=\"validateEmail1()\"/>\r\n");
      out.write("            @\r\n");
      out.write("            <input type=\"text\" name=\"email2\" id=\"email2\" class=\"input-text\" placeholder=\"이메일\" maxlength=\"20\" onfocusout=\"validateEmail2()\" />\r\n");
      out.write("            <span id=\"email1_alert\" class=\"alert\"></span>\r\n");
      out.write("            <span id=\"email2_alert\" class=\"alert\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <select name=\"email3\" id=\"email3\"  onchange=\"hotinsert(this.value)\">\r\n");
      out.write("              <option selected=\"selected\">직접입력</option>\r\n");
      out.write("              <option value=\"naver.com\" onclick=\"hotinsert('naver.com')\">gmail.com</option>\r\n");
      out.write("              <option value=\"naver.com\" onclick=\"hotinsert('naver.com')\">naver.com</option>\r\n");
      out.write("              <option value=\"hanmail.net\"  onclick=\"hotinsert('hanmail.net')\">hanmail.net</option>\r\n");
      out.write("              <option value=\"nate.com\"  onclick=\"hotinsert('nate.com')\">nate.com</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>  \r\n");
      out.write("       \r\n");
      out.write("        <tr>\r\n");
      out.write("          <th bgcolor=\"#eeeeee\" scope=\"row\">주소*</th>\r\n");
      out.write("          <td>\r\n");
      out.write("            <p>\r\n");
      out.write("\t\t\t  <input type=\"text\" name=\"sample6_postcode\" id=\"sample6_postcode\" placeholder=\"우편번호\"/>\r\n");
      out.write("\t\t\t  <input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"/><br></br>\r\n");
      out.write("\t\t\t  <input type=\"text\" name=\"sample6_address\" id=\"sample6_address\" placeholder=\"주소\"/>\r\n");
      out.write("              <input type=\"text\" name=\"daddress\" id=\"daddress\" />\r\n");
      out.write("            </p>\r\n");
      out.write("          </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        \r\n");
      out.write("      </table>\r\n");
      out.write("      \r\n");
      out.write("      <br><br><br><br>\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "joinUnder.jsp", out, true);
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <br><br>\r\n");
      out.write("        <div class=\"button-area\" style=\"margin-left: 300px;\">\r\n");
      out.write("\t\t\t<input type=\"button\" class=\"button01\" onclick=\"check()\" value=\"가입하기\"> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div class=\"button-area\" style=\"margin-left: 20px;\">\r\n");
      out.write("\t\t\t<a href=\"../index/index.jsp\" class=\"button01\">취소하기</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../form/footer.jsp", out, true);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
