/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2019-12-18 00:11:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.form;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>무제 문서</title>\r\n");
      out.write("<link href=\"../../css/layout.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write("<hr style=\"opacity: 0.4;\">\r\n");
      out.write("        <div class=\"area_contact\">\r\n");
      out.write("            <dl class=\"contact_item\">\r\n");
      out.write("                <dt><strong>인테리어소품, 코제트</strong></dt>\r\n");
      out.write("                <dd class=\"info\">\r\n");
      out.write("                    학번 2014314025<span class=\"bar\"> | </span>IT경영학과  웹프로젝트<br> 대표이사 임한응 염혜린<span class=\"bar\"> | </span>경기도 시흥시 산기대학로 237 D동 402호<br> 전화 010-9163-1670           <br>\r\n");
      out.write("                </dd>\r\n");
      out.write("                \r\n");
      out.write("                <br>\r\n");
      out.write("                <br>\r\n");
      out.write("                \r\n");
      out.write("            <a href=\"https://smartstore.naver.com/cosette_seoul\" target=\"_blank\" class=\"logo N=a:fot.navercorp\"><span class=\"blind\">COSETTE</span></a>\r\n");
      out.write("            <em>Copyright ©</em>\r\n");
      out.write("            <a href=\"https://smartstore.naver.com/cosette_seoul\" target=\"_blank\" class=\"link\"><strong>인테리어소품,코제트.</strong></a>\r\n");
      out.write("            <span>All Rights Reserved.</span>\r\n");
      out.write("            </dl>       \r\n");
      out.write("      \t</div>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"area_contact\">\r\n");
      out.write("            <dl class=\"contact_item\">\r\n");
      out.write("                <dt><strong>고객센터</strong></dt>\r\n");
      out.write("                <dd class=\"info\">\r\n");
      out.write("                    경기도 시흥시 산기대학로 237 D동 402호<br> 전화 010-9163-1670<a href=\"http://help.pay.naver.com\" class=\"N=a:fot.beforecall button_call\">전화전클릭</a><br> 결제도용신고 1588-3816<br> <a href=\"https://help.pay.naver.com/faq/alias/naver-gu.help\" target=\"_blank\" class=\"inquire_link info_link\">1:1문의 바로가기</a>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"area_contact\">\r\n");
      out.write("            <dl class=\"contact_item\">\r\n");
      out.write("                <dt><strong>전자금융거래 분쟁처리</strong></dt>\r\n");
      out.write("                <dd class=\"info\">\r\n");
      out.write("                    전화 1588-3819<br> <a href=\"https://help.pay.naver.com/faq/alias/naver-gu.help\" target=\"_blank\" class=\"inquire_link info_link\">1:1문의 바로가기</a>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<div class=\"block\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
